name: Deploy GitHub Pages Website

on:
  push:
    branches:
      - main # Adjust this if your primary branch is 'master' or something else
  workflow_dispatch: # Allows you to manually trigger the workflow from the 'Actions' tab

# Sets permissions for the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # Build job (optional, but good if you have processing steps)
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository
        uses: actions/checkout@v4

      # If you have any steps to process your data, generate figures,
      # or dynamically create HTML content, they would go here.
      # For example, running a Python script:
      # - name: Run data analysis and generate website content
      #   run: python src/website_builder.py
      #   # Ensure this script places the final HTML/images in the 'website/' directory.

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload website artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          # This is the CRUCIAL line: Tell GitHub Actions where your final website files are located.
          # This path should point to the directory that *contains* your index.html for deployment.
          path: 'website' # <--- This matches your 'website/' folder

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build # This job depends on the 'build' job completing successfully
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
